oauth:
  token_url: "https://example.com/oauth/token"
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  grant_type: "client_credentials"

tests:
  - endpoint: "https://example.com/api/resource"
    method: "POST"
    headers:
      Content-Type: "application/json"
    body:
      key1: "value1"
      key2: "value2"
    expected_status: 200
    schema:
      type: "object"
      properties:
        key1:
          type: "string"
        key2:
          type: "string"
      required: ["key1", "key2"]